### ISSUE TITLE
2-bul type keyboard has a bug. 

### ISSUE THREAD

**Issue by jaepil-choi** [navilera/NavilIME#13]
분명 두벌식으로 설정했고 ok 누르고 컴퓨터 재시작까지 했는데.... 
증상이:
- 한/영 키로 바로 한글로 바뀌지 않음. 메모장 켜서 거기서 바꿔야 한영전환 됨. 
- 한글로 바꿔도 입력시 계속 받침이 붙어 '일런식을로 낭옵닏다.'

Check out the comment of the original post: https://kldp.org/node/161067

마이크로소프트 한글 IME 키보드가 오류를 일으키는 지점에 새로운 대체재를 제공한다는 점에서 나빌레라 키보드의 두벌식 기능에 큰 의의가 있다고 생각합니다.

**Comment by navilera** [comment]
버그 리포트 감사합니다.

## 원인
개발할 때 두벌식을 고려하지 않았습니다. 

libhangul이 글자 automata를 완성했을 때, 세벌식은 마지막 편집 중인 글자가 항상 automata가 완성된 글자와 같습니다. 그래서 글자가 완성될 때, 마지막 편집 중인 글자를 그대로 complete하게 동작합니다.

두벌식일 때는 automata의 완성 여부를 다음 글자의 초성 입력 이후에 확정할 수 있습니다. 그래서 automata가 완성되는 글자가 받침이 없는 글자일 때, 편집 중인 글자는 종성이 있는 상태입니다. 이 종성은 원래 다음 글자의 초성이죠. 이 현상이 바로 **도깨비불 현상**입니다. 세벌식은 도깨비불 현상이 없어서 고려를 안했습니다.

도깨비불 현상 상태에서 입력중인 글자를 그대로 complete 해버리기 때문에 받침이 붙어서 입력됩니다.

## 해결방법
libhangul이 automata 완성을 알리면 libhangul로부터 완성된 글자를 받아서 현재 입력중인 글자를 업데이트하고 complete합니다.

**Comment by navilera** [comment]
정식 릴리즈는 아니지만 https://github.com/navilera/NavilIME/raw/master/Release/Installer/NavilIme-2.2.0.exe 를 다운받아 설치하면 본 이슈를 해결한 나빌 입력기를 쓸 수 있습니다.

**Comment by jaepil-choi** [comment]
안녕하세요, 버그 수정 감사합니다!

그런데 2.2를 다운받아 설치한 후 실행해도 여전히 문제가 발생하는데 혹시 제가 2.1을 clean uninstall하지 않고 그냥
2.2를 다운받아 설치해서 그런건가 싶기도 합니다.

나빌레라 키보드를 삭제해보려고 했는데 제어판의 프로그램 추가제거같은 곳을 가도 딱히 삭제할 수 있는 uninstall.exe 파일
같은게 없더라고요.... 나빌레라 이전 버전 삭제는 어떻게 하면 될까요?

감사합니다.

Best Regards,
Jaepil Choi

**Comment by navilera** [comment]
언인스톨러는 별도로 배포하고 있습니다.

https://github.com/navilera/NavilIME/tree/master/Release/Uninstaller

**Comment by Obami-Morrow** [comment]
언인스톨러 다운받아 삭제하려고 하였는데 다음과 같은 메세지가 뜹니다.
64bit app: Explorer.EXE
32bit app: _uninstaller.exe

위 프로그램을 종료하고 Reload를 눌러주세요..

Please close the above programs and click 'Reload' button..

프로그램 이름으로 인식하는것 같아 NavilIME_uninstaller.exe는 파일명은 변경하였으나 여전히 종료 후 삭제 가능하다고 합니다.(explorer도 닫아야 하는게 좀 이상합니다)

**Comment by navilera** [comment]
> 언인스톨러 다운받아 삭제하려고 하였는데 다음과 같은 메세지가 뜹니다.
> 64bit app: Explorer.EXE
> 32bit app: _uninstaller.exe
> 
> 위 프로그램을 종료하고 Reload를 눌러주세요..
> 
> Please close the above programs and click 'Reload' button..
> 
> 프로그램 이름으로 인식하는것 같아 NavilIME_uninstaller.exe는 파일명은 변경하였으나 여전히 종료 후 삭제 가능하다고 합니다.(explorer도 닫아야 하는게 좀 이상합니다)

윈도우의 TSF 구조가 원래 그렇습니다. 나빌 입력기를 설정해 놓은 상태에서 한 번이라도 실행한 프로그램은 무조건 나빌 입력기 DLL을 임포트합니다. explorer(탐색기)도 예외없습니다. 

언인스톨러의 파일명을 바꾸는것은 추천하지 않습니다.

깔끔하게 언인스톨하고 싶으시면 입력기를 나빌 입력기가 아닌 다른 입력기(윈도우 기본 입력기같은..)로 바꾸고 재부팅한다음, 재부팅 하자마자 언인스톨러를 실행해 주세요.

**Comment by Obami-Morrow** [comment]
알려주신 방법대로 언인스톨 했습니다.
사실 사용방법이 아니라 언인스톨부터 여쭤봐서 언짢으셨을 수도 있으실 텐데 친절히 설명해 주셔서 감사합니다.

원노트 한글 씹힘 현상 때문에 알게되었는데 제 원노트에서는 나빌 입력기가 한영전환이 되지 않더라구요. 이래저래 시도하다 옛한글 IME 적용했더니 한글씹힘현상이 없어졌습니다.

다음에 기회가 된다면 또 사용하도록 하겠습니다
감사합니다.

**Comment by navilera** [comment]
> 알려주신 방법대로 언인스톨 했습니다.
> 사실 사용방법이 아니라 언인스톨부터 여쭤봐서 언짢으셨을 수도 있으실 텐데 친절히 설명해 주셔서 감사합니다.
> 
> 원노트 한글 씹힘 현상 때문에 알게되었는데 제 원노트에서는 나빌 입력기가 한영전환이 되지 않더라구요. 이래저래 시도하다 옛한글 IME 적용했더니 한글씹힘현상이 없어졌습니다.
> 
> 다음에 기회가 된다면 또 사용하도록 하겠습니다
> 감사합니다.

한영전환은 한/영 키가 아니라 shift+space로 해 보세요. (한/영키도 아마 잘 되긴 할텐데 이상하군요)

**Comment by Obami-Morrow** [comment]
물론 shift+space도 해봤습니다. 유독 원노트에서만 안되더군요. 다른 프로그램에서는 잘 동작했었습니다. 나빌레라님 블로그 였나? 어디에서도 동일한 증상을 말씀하신 분이 있었는데 '바본가 한영전환이 외않되' 하고 그냥 넘어갔었던 제가 바보였습니다.

**Comment by navilera** [comment]
윈도우10에서 쓸 수 있는 원노트가 두 종류가 있다는 사실을 얼마전에 알았습니다. 윈도우 앱 스토어에서 받을 수 있는 무료 원노트와 오피스 패키지에 포함되어 있는 원노트 두 종류가 있더라구요.
오피스 패키지에 포함된 원노트에서 나빌 입력기는 잘 동작합니다.

윈도우 앱 스토어에서 받을 수 있는 무료 원노트에서 나빌 입력기를 로딩을 안하는 현상이 있었습니다. 
https://github.com/navilera/NavilIME/tree/master/Doc/ReleaseNotes_2.3
새로 릴리즈한 2.3 버전에서 해당 현상이 사라진것으로 보입니다. 이제 무료 버전 원노트에서도 나빌 입력기를 쓸 수 있습니다.

**Comment by jaepil-choi** [comment]
개발자님 안녕하세요,

나빌 2.3 사용해보았습니다. 원노트에서도 작동하는 것 같네요. 그런데 2.3에 치명적 버그가 있는 것 같아 리포팅 합니다.

동영상 보시면 글자가 먹히거나 중복 입력되는 경우가 존재합니다. 두벌식 세팅으로 사용하였습니다.

참고하세요 ~

Best Regards,
Jaepil Choi

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/30/20,
04:15:22 AM
