### ISSUE TITLE
IME인스톨 후 한국어 입력기 일람에서 사라지는 현상

### ISSUE THREAD

**Issue by JungWonYong** [navilera/NavilIME#14]
먼저 한국어로 작성하는점 사과드립니다. 
가능하면 영어로 작성하려고 생각은 했는데, 내용을 제대로 설명을 할 수 있을지 불안해서 한글로 적습니다. 
혹시 영어로 작성해야 하는 경우 말씀해 주시면 나중에 열심히 영어로도 옮겨 보겠습니다. 

발생 환경 
Windows 2016 Server (Microsoft Windows [Version 10.0.14393]) 
-> AWS Workspaces환경이라 실 머신은 아니고 가상환경입니다.

캡춰의 표시 언어가 일본어인 점 양해 부탁드립니다. (AWS리젼문제로 윈도우 표시언어가 영어랑 일본어만 있네요. 언어팩 설치하면 한국어도 설치는 가능할것 같습니다만..)
먼저 인스톨러로 인스톨 한 후 입력기를 추가 하려고 제어판쪽에서 입력기를 추가 했습니다.
![image](https://user-images.githubusercontent.com/40050465/72450517-dbaca600-37fd-11ea-8e1b-9355c1f59569.png)
![image](https://user-images.githubusercontent.com/40050465/72450701-27f7e600-37fe-11ea-9ae1-200c9e59fe79.png)
![image](https://user-images.githubusercontent.com/40050465/72450766-3ba34c80-37fe-11ea-9179-96019e36e519.png)
![image](https://user-images.githubusercontent.com/40050465/72450789-49f16880-37fe-11ea-8cb5-8a6911eb4f3c.png)
저장을 누르고 나서 리스트로 돌아갔는데 입력기가 사라집니다.(다시 들어가보면 없습니다.)
![image](https://user-images.githubusercontent.com/40050465/72450841-58d81b00-37fe-11ea-9118-3bd703eaeda9.png)

그런데 신기한점은 단축키를 지정하는 화면쪽에는 들어가 있습니다. 단축키를 지정하고 눌러보면 전환이 잘 됩니다.
![image](https://user-images.githubusercontent.com/40050465/72450971-92a92180-37fe-11ea-9fcd-121be7fb9bc4.png)

아마도 실제적으로 입력기는 등록이 되었으나, 윈도우의 관리용 형식적인 데이터중에 뭔가가 부족한 듯 싶습니다.

**Comment by JungWonYong** [comment]
네이티브 프로그램인 메모장이나 텍스트 에디터에서는 문제가 없는데, 브라우저(크롬)에서 이 github페이지에서 입력을 하다보니 글자가 사라지는 현상이 발생하는데 발생 조건을 아직 알수가 없어, 나중에라도 정리되면 이슈로 올려보도록 하겠습니다. 음..

**Comment by navilera** [comment]
Windows 2016 이라는 것도 있군요. 처음보는 버전 이름입니다. 해당 문제는 TSF를 이용해서 추가로 UI를 더 구현해야 설정 화면에서 볼 수 있습니다. 그런데 자료가 너무 없고 기존 중국어나 일본어 입력기 코드를 분석하니 구현 자체가 어렵더군요. 그래서 구현하지 않았습니다. 차선책으로 Control Panel (https://github.com/navilera/NavilIME/tree/master/Release/ControlPanel)을 별도로 구현해서 패키지에 포함했습니다. 최종적으로는 Control Panel의 기능을 언급하신 윈도우 설정으로 넣는 것이 바람직합니다만, 현재 나빌 입력기에 설정할 기능이 별로 많지 않아 구현을 미루고 있는 중입니다. 누군가 해 줬으면 좋겠군요. (오픈 소스인데..)

**Comment by navilera** [comment]
해당 문제는 크롬이 원래 가지고 있던 한글 끝 글자 버그를 패치하면서 생긴 문제입니다. 크롬을 뭘 어떻게 바꾼건지 모르겠는데 크롬 버전업을 하면서 나빌입력기에서 그 문제가 생깁니다. 제가 크롬을 쓰지 않아 불편함이 없어서 동기부여가 안되어 작업을 안하고 있습니다.

파이어폭스에 문제가 생겼으면 바로 고쳤을 텐데 말이죠.

엄밀히 따지면 크롬의 문제이지만 안 유명한 프로그램이 유명한 프로그램을 지원할 수 밖에 없으니 이슈는 계속 열어 두겠습니다.

**Comment by JungWonYong** [comment]
답변 감사합니다. 귀가가 늦어져서 지금 확인했습니다.

우선 윈도우즈 2016 서버 버전은 일반용으로는 윈도우즈10에 해당하긴 합니다만, 이것저것 일반적인 용도에는 불필요한게 잔뜩 들어있습니다. 저도 일반 윈도우가 있었으면 좋았었는데... 아마도 AWS에서 제어하려면 서버버전 이라야 하는가봅니다. EC2의 윈도우즈 인스턴스가 죄다 서버 버전일걸 보니.. 

음.. 윈도우 설정 구현 쪽은 잘 알았습니다. 제가 윈도우 개발자는 아니지만 자료는 한번 찾아보고 공부해봐야겠네요.
(이게 리눅스쪽 이야기면 좀더 의욕이 크게 생길것 같습니다만...)
그런데 윈도우는 비주얼 스튜디오가 커뮤니티 버전이 무료화 되긴 했지만 옛날 코드나 이것저것 필요한 기능을 쓰려면 유료 버전을 써야 하는 걸로 들었는데, 혹시 현재 컴파일에 사용하고 계신 환경은 무료환경인가요? 
공부하면서 하려면 우선 빌드환경부터 만들어야 할 것 같아서요... (제가 그나마 할줄아는건 gcc make나 JAVA쪽 maven정도라 - -;)

브라우저 문제는 크롬 자체의 버그였군요. 사실 저도 기본적으로는 파이어폭스 유저입니다만... 저 글을 쓸때 마침 크롬으로 검색하다가 KLDP쪽에 올리신 글이 히트했던 참이라서 ㅜ.ㅜ
이 이슈 제목은 제어판에서 사라지는 현상이니, 크롬 건은 이슈를 따로 등록하고, 이 건은 닫는것이 어떨까 싶습니다.

**Comment by navilera** [comment]
저도 윈도우 프로그래밍은 인터넷 찾아서 짜집기하는 수준입니다. 개발환경은 비주얼 스튜디오 최신버전 커뮤니티 에디션? 이던가.. 무료 버전있습니다. 그거 쓰시면 됩니다. 본 이슈는 그럼 닫겠습니다.
