### ISSUE TITLE
Chrome 브라우저에서 한글 입력시 입력한 글자가 사라지고 다음 글자가 들어가는 현상.

### ISSUE THREAD

**Issue by JungWonYong** [navilera/NavilIME#15]
・발생환경
OS : Windows 10 (Windows 2016 server) 64bit
발생 프로그램 : Google Chrome Browser ( ver 70.0.3945.117 ) 64bit
![image](https://user-images.githubusercontent.com/40050465/72534739-a74aef80-38ba-11ea-9400-5677c3312081.png)

・증상
크롬 브라우저의 제목창이 및 표시중인 웹 페이지의 입력란(text line, text area 상관없음)에 글자를 입력중에, 먼저 입력한 글자가 확정되지 않고 뒤에 입력한 글자가 나타남.
 예) 크롬에서 "한국어" 입력시
![ezgif-3-e63617cef910](https://user-images.githubusercontent.com/40050465/72535689-4f14ed00-38bc-11ea-992d-82668ec04e54.gif)

 받침이 없는 글자를 입력하면 문제없이 들어갑니다. (아마도 한글자의 끝을 제대로 파악하지 못하는 듯한 느낌입니다.)
![ezgif-3-b1b41aea91e7](https://user-images.githubusercontent.com/40050465/72535987-ce0a2580-38bc-11ea-9dff-ee6a242019dd.gif)

**Comment by navilera** [comment]
크롬 최신 버전에서 고쳐진것으로 보입니다.
확인 부탁드려요.
확인 해 주시면 이 이슈는 닫겠습니다.

**Comment by JungWonYong** [comment]
시간이 걸려서 죄송합니다. 
한동안 윈도우즈를 기동하지 않다가 다시 기동하였더니 윈도우 업데이트가 자동 진행되었고, 
이후 크롬을 최신 버전으로 갱신하고, Navil IME 2.3  버전을 설치하여 테스트 해 보니 다음과 같았습니다.
다만, 크롬 뿐 아니라 메모장 등 다른 프로그램도 동일한 증상이 나타나고 있어 저의 환경문제인것으로 생각됩니다. 

죄송하지만 아마도 환경을 고치려면 시간이 좀 걸릴듯 합니다.
디만 다른 어플리케이션과 동일한 동작을 하는것을 확인했으므로 일단 이 이슈는 닫아도 괜찮을 것 같습니다.

![画面収録-2020-07-17-18 16 29](https://user-images.githubusercontent.com/40050465/87770773-6bd5b180-c85a-11ea-8409-4f7900228257.gif)
