### ISSUE TITLE
파일 탐색기(explorer.exe)에서 폴더 경로 수정시 받힘이 제대로 입력되지 않음

### ISSUE THREAD

**Issue by MinkiDev** [navilera/NavilIME#16]
# Environments
    OS Version: Windows 10 Pro v1909 @ Build 18363.720
    Process: explorer.exe

# Screenshots
> '난난난앙앙앙핳핳핳' 입력을 의도한 경우

![image](https://user-images.githubusercontent.com/29994623/77171478-d9b5da80-6aff-11ea-987b-a13aa85c248e.png)

**Comment by navilera** [comment]
제 시스템에서 재현이 안됩니다. 조금더 자세한 정보를 요청드립니다.

![navilime_exploror](https://user-images.githubusercontent.com/4327207/77843356-3b55f480-7151-11ea-8936-2a285b9eaa27.png)

**Comment by MinkiDev** [comment]
당시 Windows 표시 언어/기본은 한국어이며,
설치된 IME는 기본 한글 입력기, English, Japanese 로 총 3개였습니다.
혹시 Microsoft 한글 입력기와 충돌이 발생할 수 있을까요?

현재는 제 시스템도 OS 로케일을 영어로 변경한 상태라 재현이 어려울 것 같습니다.
