### ISSUE TITLE
<Esc> 영문 전환 설정 건의

### ISSUE THREAD

**Issue by kjoonlee** [navilera/NavilIME#19]
안녕하세요,

`<Esc>`를 누르면 (자소 compose 도중이라면 commit가 되면서) 영문 입력 모드로 전환되는 기능을 예전에 새나루에서 즐겨 썼습니다. Checkbox로 이 기능 사용 여부를 설정할 수 있었습니다.

Vim 사용 중 익숙해졌던 기능이라 NavilIME에도 비슷한 기능 추가를 건의드리오니 검토 부탁드립니다. 감사합니다.

**Comment by navilera** [comment]
되긴 되는데 ESC를 연속 두 번 눌러야 됩니다.
