### ISSUE TITLE
안마태 자판 지원해 주실 수 없으신지요?

### ISSUE THREAD

**Issue by solidsnake9** [navilera/NavilIME#21]
libhangul에는 있는데 삭제 당한 듯 하여 부탁드립니다.
이미 구현되어 있는 자판이므로 간단한 작업이었으면 좋겠습니다.
dvorak, 안마태 이렇게 사용하고 있습니다.

감사합니다.

**Comment by navilera** [comment]
간단한 작업입니다. 그러나 자판 동작을 검증할 수 없어서 (안마태 자판 사용자를 찾을 수 없어서) 인터페이스에서 연결을 안했을 뿐입니다.
프로그램 수정없이도 안마태 자판을 쓸 수 있습니다. 자판 동작을 테스트해 주신다면 안마태자판으로 레이아웃을 수동으로 변경하는 방법을 알려드리겠습니다.

solidsnake9님이 안마태 자판의 동작이 잘 됨을 확인한 후에 코드 수정후 버전업하는 것이 더 좋아보입니다.

**Comment by solidsnake9** [comment]
당연히 테스트 하고 싶습니다!
구름입력기에서도 한글이 아니라 영문이 입력되는 상황이었는데도 아무도 모르고 계셨더라고요.
마이너 자판의 숙명이 아닌가 싶습니다.
오토마타가 이어치기든 모아치기든 사용할 수는 있으나 제대로 쓰려면 역시 모아치기로 되어 있다면 좋겠습니다.
일단 테스트 후 말씀드리겠습니다.

감사합니다.

**Comment by navilera** [comment]
아마 Issue #20 과 연결되어서 모아치기는 안될지도 모르겠습니다.

현재 Program Files/NavilIME 와 Program Files(x86)/NavilIME 폴더에 들어가면 Keyboard.dat 파일이 있습니다. 이 두 파일의 첫 줄을 'ahn' (따옴표없이 ahn)으로 바꾸고 저장한 다음, 재부팅하고 나면 안마태 자판이 됩니다.

테스트해 보시고 커맨트 달아 주세요.

**Comment by solidsnake9** [comment]
아,  짐작이 가능한 히든 커맨드였네요. 왜 시도해볼 생각을 못 했는지.
감사합니다! 정말 잘 작동하며 구름입력기나 날개셋의 이어치기-모이치기 겸용 모드 처럼 동작합니다.
이른 아침부터 도움 주셔서 정말 감사합니다!

추가 건의 사항으로 영문자판의 확장도 말씀드려봅니다.

다시 한 번 감사드립니다!

**Comment by navilera** [comment]
테스트 감사합니다. 당분간은 알려드린 방법으로 안마태 자판 사용해 주세요.
간단한 추가라서 다음 릴리즈에서 바로 적용하겠습니다.

**Comment by ietzhayim** [comment]
죄송합니다만, 맥에 안마태 자판만을 추가해서 사용하고 싶은데 방법을 알려주실 수 있을까요?
