### ISSUE TITLE
나빌(NavilIME) 한글 입력기를 제거하는 방법?

### ISSUE THREAD

**Issue by cwork2018** [navilera/NavilIME#25]
github 사용을 잘 할줄몰라서 여기에 질문을 남겨도 되는지 모르겠습니다만, 달리 연락할 방법을 몰라서 질문드립니다.

관리자 권한으로 윈도우 커맨드를 실행후 아래의 방법을 실행했습니다. 그런뒤에 NavilIME 폴더도 삭제했습니다.
그런데 문제는 사진처럼 윈도우즈10 작업표시줄의 언어 선택에 여전히 NavilIME가 남아있습니다.
남기만 하면 신경끌수도 있겠지만, 문제는 뭘하다가 키보드의 한/영을 눌러서 한글 입력하려고 하면 영어만 입력이되어서
보니까 NavilIME가 선택이 되어있어서 언어 아이콘 누른뒤 "한국어 Microsoft 입력기"를 선택해줘야 하는 경우가 비일비재합니다. 제가 NavilIME가 선택안해도 이런 문제가 계속 생기는군요.

regsvr32 /u "c:\Program Files\NavilIME\NavilIME.dll"
regsvr32 /u "c:\Program Files (x86)\NavilIME\NavilIME.dll"

![NavilIME](https://github.com/navilera/NavilIME/assets/45278870/49a8b150-ea8c-4d72-938b-d4c48a62767e)

**Comment by navilera** [comment]
수동으로 삭제 하셨나보군요. 아마 뭔가 빼먹었을겁니다.

인스톨 할 때 같이 설치되는 언인스톨러로 지워 주세요.

혹은 https://github.com/navilera/NavilIME/tree/master/Release/Uninstaller 여기서 언인스톨러 다운 받아서 실행하여 지워주세요.

**Comment by cwork2018** [comment]
얘기해주신 아래의 위치에서 NavilIME_Uninstaller_2_1.zip 를 다운받아 풀어서 관리자 권한으로 실행해서 uninstall 했는데도 여전하군요.

https://github.com/navilera/NavilIME/tree/master/Release/Uninstaller

uninstall 한뒤 리부팅해도 여전하고, 또다시 uninstall 실행한뒤 컴퓨터 종료했다가 다시 켜도 여전합니다.
여전하다는 의미는 "윈도우즈10 작업표시줄의 언어 선택에 여전히 NavilIME가 남아있다" 라는 의미입니다.

![navillme2](https://github.com/navilera/NavilIME/assets/45278870/48ae82a6-bdfa-47ae-9754-b5c5246e34bc)

**Comment by cwork2018** [comment]
> 수동으로 삭제 하셨나보군요. 아마 뭔가 빼먹었을겁니다.
> 
> 인스톨 할 때 같이 설치되는 언인스톨러로 지워 주세요.
> 
> 혹은 https://github.com/navilera/NavilIME/tree/master/Release/Uninstaller 여기서 언인스톨러 다운 받아서 실행하여 지워주세요.


얘기해주신 아래의 위치에서 NavilIME_Uninstaller_2_1.zip 를 다운받아 풀어서 관리자 권한으로 실행해서 uninstall 했는데도 여전하군요.

https://github.com/navilera/NavilIME/tree/master/Release/Uninstaller

uninstall 한뒤 리부팅해도 여전하고, 또다시 uninstall 실행한뒤 컴퓨터 종료했다가 다시 켜도 여전합니다.
여전하다는 의미는 "윈도우즈10 작업표시줄의 언어 선택에 여전히 NavilIME가 남아있다" 라는 의미입니다.

![navillme2](https://github.com/navilera/NavilIME/assets/45278870/e91d9f26-ed02-47d9-8b06-b80853bab4a6)

**Comment by navilera** [comment]
시스템에 별로 해롭지 않으니 아래 순서대로 언인스톨 시도해 보세요
1. 나빌입력기 다시 설치
2. 나빌입력기 동작 확인 - 동작되어야 함
3. 입력기를 변경 (나빌입력기가 아닌 윈도우 입력기 아무거나)
4. 재부팅
5. 입력기가 나빌입력기가 아닌 상태여야 함.
6. 나빌입력기로 변환을 하면 안됨
7. 나빌입력기로 변환한 상태에서 실행한 프로그램이 없어야 함. (그래서 재부팅하자마자 언인스톨하는것을 추천합니다.)
8. 나빌입력기 언인스톨러 실행 - 관리자 권한, 에러 메시지 없이 언인스톨이 되어야함
9. 재부팅
