### ISSUE TITLE
32bit 프로그램(notepad++)에서 한글 입력이 안됩니다.

### ISSUE THREAD

**Issue by fehead** [navilera/NavilIME#3]
아마 32비트 프로그램은 입력이 안될까 싶은데요.
32bit notepad++ 에서 한글 입력(한글 전환)이 안되네요.

notepad++ 32bit 포터블 버전입니다.

https://notepad-plus-plus.org/repository/7.x/7.6.3/npp.7.6.3.bin.minimalist.7z

좋은 프로그램 잘 사용하고 있습니다.

**Comment by navilera** [comment]
원인
-----
나빌 입력기는 64비트 바이너리만 배포하고 있습니다.

해결 방법
-----------
두 가지 방법 중 하나를 선택해 문제를 해결 할 수 있습니다.
1. 64비트 notepad++을 사용합니다.
1. 나빌 입력기 소스 코드로 32비트 바이너리를 빌드합니다.
 * program files(x86)에 나빌 입력기를 설치합니다.

할일
----
가장 좋은 해결 방법은 32비트 나빌 입력기 바이너리를 배포하는 것입니다.
단순히 32비트 바이너리와 64비트 바이너리를 같이 배포하는 것으로 문제는 해결되지만 그 때문에 설치과정이 복잡해 집니다. 따라서 인스톨러를 만들어야 합니다.
위 내용으로 새로운 이슈를 생성하고 이 이슈는 닫습니다.
새로운 이슈: [#4][#5]
